spring:
  application:
    name: msUsers
  datasource:
    url: jdbc:h2:mem:usersdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
jwt:
  secret:  thisisatestingkeyisatestingkeyforhs256THISISATESTINGKEYISATESTINGKEYFORHS256